spring.application.name=appointment-service

server.port=8083


# ===============================
# Database
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/mediverse_appointments
spring.datasource.username=root
spring.datasource.password=Monu@123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false


# ===============================
# Doctor Service
# ==============================


# ===============================
# JWT
# ===============================

jwt.secret=MediverseSecretKeyForDevelopmentOnly123456789


doctor.service.url=http://localhost:8082
# ===============================
# Logging
# ===============================

logging.level.com.mediverse.appointmentservice=INFO


# eureka client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
