spring.application.name=pharmacy-service
server.port=8086

# ===============================
# MySQL Database
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/mediverse_pharmacy
spring.datasource.username=root
spring.datasource.password=Monu@123

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# JWT
# ===============================
jwt.secret=MediverseSecretKeyForDevelopmentOnly123456789

# ===============================
# Other Services
# ===============================
services.prescription-service.url=http://localhost:8085

# ===============================
# Multipart - External Prescription
# ===============================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# eureka client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
